vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        consultant_file:
            uri_prefix: /images/consultants
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer